# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

collections:

  - name: "community.docker"
    version: "2.4.0"

roles:

  - name: "geerlingguy.docker"
    src: "geerlingguy.docker"
    version: "4.2.2"

  - name: "geerlingguy.pip"
    src: "geerlingguy.pip"
    version: "2.1.0"

...
