# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Converge"
  hosts: "all"
  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: "ansible_os_family == 'Debian'"

    - name: "Wait for systemd to complete initialization"  # noqa command-instead-of-module
      ansible.builtin.command: "systemctl is-system-running"
      register: "systemctl_status"
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: "ansible_service_mgr == 'systemd'"
      changed_when: false
      failed_when: "systemctl_status.rc > 1"
      check_mode: no
  tasks:
    - name: "Include research-software-directory"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
