# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Prepare"
  hosts: "all"
  vars:
    docker_daemon_options:
      storage-driver: "vfs"
      default-runtime: "crun"
      runtimes:
        crun:
          path: "/usr/bin/crun"
    pip_install_packages:
      - name: "docker"
        state: "absent"
      - name: "docker-compose"
        state: "present"
      - name: "requests"
        state: "present"
  tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      when: "ansible_os_family == 'Debian'"

    - name: "Install crun container runtime"
      ansible.builtin.apt:
        name: "crun"
        state: "present"

    - name: "Apply geerlingguy.pip role"
      ansible.builtin.include_role:
        name: "geerlingguy.pip"

    - name: "Apply geerlingguy.docker role"
      ansible.builtin.include_role:
        name: "geerlingguy.docker"

    - name: "Copy TLS files"
      ansible.builtin.copy:
        src: "{{ item.file }}"
        dest: "{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - { file: "{{ tls_cert_file }}", dest: "/etc/ssl/certs/rsd.pem", mode: "0644" }
        - { file: "{{ tls_key_file }}", dest: "/etc/ssl/private/rsd.key", mode: "0600" }
        - { file: "{{ nginx_dhparam_file }}", dest: "/etc/ssl/private/dhparam.pem", mode: "0600" }
